# --- Configuração do Servidor ---
spring.application.name=zenith
server.port=${PORT:8080}

# --- Banco de Dados MySQL ---
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configurações do JPA ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- Banco de Dados MongoDB ---
spring.data.mongodb.host=mongodb.railway.internal
spring.data.mongodb.port=27017
spring.data.mongodb.database=zenith_db
spring.data.mongodb.username=mongo
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.authentication-database=admin

# --- Segurança JWT ---
zenith.jwt.secret=${JWT_SECRET}
zenith.jwt.expiration-ms=86400000
